version: 2
jobs:
  build:
    working_directory: ~
    docker:
      - image: circleci/python #image docker

    steps:
      - checkout
      - run:
          command: |
            sudo pip install -r requirements.txt
            pytest
      - store_test_results:
        path: test-results
      - store_artifacts:
        path: test-results
        destination: trl
